### PR TITLE
Version mismatch for build, Log Location Config option & more consistant looks

### PR DESCRIPTION
**Pull request by ThePjpollie**
- Changed the version of `electron-updater` so you can build the way the project is setup.
- Changed 2 lines that has a ligher background. This to keep consistant columns lighting in config tab
- Added Log Location config on request of @Kermalis

### CODE REVIEW

**Comment by Barbosicks** [comment]
The electron-updater version is on purpose.

**Comment by ThePjpollie** [comment]
Oh, sorry. Strange. It told me I had the wrong version, changed it and was fixed. Will check again later today

**Comment by Barbosicks** [comment]
I don't know what the -w option is, but we only pack with electron-builder and then use Inno for the setup.

**Comment by ThePjpollie** [comment]
chrome_2018-07-14_16-19-17
I followed the readme of this repo :P 

Mind giving more information on how you guys build & setup?

**Comment by ThePjpollie** [comment]
Alright, thanks for the info! Reverted version back to the old one :)

**Pull request merged**
